### ISSUE TITLE
how to add json_kwargs?

### ISSUE THREAD

**Issue by GEmilioHO** [LucaCappelletti94/compress_json#1]
Hi, 

It might be a silly question, but I'm struggling to add **json_kwargs**.  I am trying the following:

`compress_json.local_dump(ng.data, outfile, json_kwargs  = {"indent": 4}) `

But I get the following:

> TypeError: join() argument must be str, bytes, or os.PathLike object, not 'TextIOWrapper'

How could I properly add the json_kwargs?

**Comment by LucaCappelletti94** [comment]
Hello @GEmilioHO, could you please provide a small reproducible example, maybe using [Colab](https://colab.research.google.com/)? It would greatly help me out in debugging this. 

Thanks!

**Comment by GEmilioHO** [comment]
Hi @LucaCappelletti94,

I just realised that it was my mistake. I was trying to use `compress_json.local_dump()` instead of `compress_json.dump()` for adding the **json_kwargs**.

With `compress_json.dump()`, the  **json_kwargs** work perfectly! 

Thank you!
