### ISSUE TITLE
Lack of a License

### ISSUE THREAD

**Issue by ducalpha** [LucaCappelletti94/compress_json#2]
I want to include the code of the tool to one of our project. The [pypi page](https://pypi.org/project/compress-json/) says `compress_json` uses the MIT license but there is no license included on the github directory. 

From [GitHub license guidelines](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository): 
> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work

Could you please add a `LICENSE` file?

**Comment by LucaCappelletti94** [comment]
On it, I was quite sure I had added it at the beginning of the project.

**Comment by LucaCappelletti94** [comment]
Done, do let me know if that's enough. I hope the package is handy, if you have any feedback please do let me know.

**Comment by ducalpha** [comment]
Thank you for adding the `LICENSE` file!
