### ISSUE TITLE
Feature request: Show explicit example for kwargs

### ISSUE THREAD

**Issue by jgarte** [LucaCappelletti94/compress_json#3]
Hi, would it be possible to show a "real example" here of how it would be called with the kwargs?

https://github.com/LucaCappelletti94/compress_json#advanced-usage

**Comment by LucaCappelletti94** [comment]
Sure, let's see what I can put in there. Brb.

**Comment by LucaCappelletti94** [comment]
I have tried to document it a bit better. How do you feel about the current version of the README?

**Comment by jgarte** [comment]
TBH, I still think it can be better :) 

A concrete example speaks a thousand examples. 

I think the use of the word `forwarded` is also a bit confusing. I'll try to improve it and submit a PR for you to review soon. I'm just a bit busy at the moment with work.

Nonetheless, thanks for trying to improve it. It is much appreciated.

**Comment by LucaCappelletti94** [comment]
Sure, though, there is an evident difficulty as those parameters depend on third-party libraries. Is there a specific use case that you would need?
