### ISSUE TITLE
Feature request: documentation site

### ISSUE THREAD

**Issue by jgarte** [LucaCappelletti94/compress_json#4]
Similar to https://github.com/lucianopaz/compress_pickle/tree/master/docs

WDYT

**Comment by LucaCappelletti94** [comment]
I never actually came around to making what I would call a decent web-documentation. Are you experienced with that? Would you like to help?

**Comment by jgarte** [comment]
Sure, I can help with that. Just give me till the end of this month to do it.

**Comment by LucaCappelletti94** [comment]
Sure, absolutely no rush on my part!
